#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

import sys
import os.path
sys.path.append(os.path.dirname(__file__))

from grcqt.companion import main

"""
Companion should handle the main launch of everything.
Initialize the platform and model, then launch the GUI.
"""

if __name__ == "__main__":
    import sys

    # Initialize the flowgraph model

    # Setup the main qt application and window
    app = QtWidgets.QApplication(sys.argv)

    # Get the icon path. Will be relative to this script so define it here.
    icon_path = 'grc/companion/resources/logo/gnuradio_logo_icon-square-150x150-white.png'

    # Initialize the GUI
    controller = main.MainController()
    controller.set_icon(icon_path)
    controller.start()

    # Launch the qt app
    sys.exit(app.exec_())
